<a href="https://colab.research.google.com/github/KALGonzalez/ClasesDS-/blob/main/Archivos%20colab/CLASE_5_Calculo_y_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

En Python, el álgebra lineal se puede trabajar fácilmente con la biblioteca **NumPy**, que ofrece funciones y métodos eficientes para operaciones con vectores y matrices.

Aquí te muestro un ejemplo práctico usando NumPy para resolver un sistema de ecuaciones lineales, calcular autovalores y autovectores, y hacer una descomposición en valores singulares.

### Paso 1: Importar NumPy
```python
import numpy as np
```

### Ejemplo 1: Resolver un sistema de ecuaciones lineales

Supongamos que tenemos el sistema de ecuaciones:
\[
2x + 3y = 8
\]
\[
x - y = 1
\]

Podemos escribirlo en forma de matrices:
\[
AX = B
\]
donde
\[
A = \begin{bmatrix} 2 & 3 \\ 1 & -1 \end{bmatrix}, \quad B = \begin{bmatrix} 8 \\ 1 \end{bmatrix}
\]

```python
# Definir la matriz A y el vector B
A = np.array([[2, 3], [1, -1]])
B = np.array([8, 1])

# Resolver para X
X = np.linalg.solve(A, B)
print("Solución del sistema de ecuaciones (valores de x y y):", X)
```

### Ejemplo 2: Calcular autovalores y autovectores

Supongamos que tenemos una matriz cuadrada:
\[
M = \begin{bmatrix} 4 & 2 \\ 1 & 3 \end{bmatrix}
\]

```python
# Definir la matriz M
M = np.array([[4, 2], [1, 3]])

# Calcular autovalores y autovectores
autovalores, autovectores = np.linalg.eig(M)
print("Autovalores:", autovalores)
print("Autovectores:\n", autovectores)
```

### Ejemplo 3: Descomposición en Valores Singulares (SVD)

Supongamos que queremos descomponer la matriz M en sus componentes de SVD.

```python
# Descomposición en valores singulares
U, S, VT = np.linalg.svd(M)
print("Matriz U:\n", U)
print("Valores Singulares (S):", S)
print("Matriz VT:\n", VT)
```

### Explicación de los Resultados
1. **Sistema de Ecuaciones**: La solución `X` contiene los valores de \( x \) e \( y \) que resuelven el sistema.
2. **Autovalores y Autovectores**: Los autovalores indican la escala de transformación en cada dirección, y los autovectores son las direcciones de transformación.
3. **SVD**: La descomposición SVD descompone `M` en tres matrices (`U`, `S`, y `VT`), lo cual es útil en reducción de dimensionalidad y compresión de datos.

Estos son algunos ejemplos básicos, pero NumPy ofrece muchas otras funciones para operaciones avanzadas en álgebra lineal que son fundamentales en ciencia de datos.

In [ ]:
import numpy as np

# Definir la matriz A y el vector B
A = np.array([[2, 3], [1, -1]])
B = np.array([8, 1])

# Resolver para X
X = np.linalg.solve(A, B)
print("Solución del sistema de ecuaciones (valores de x y y):", X)
# Definir la matriz M
M = np.array([[4, 2], [1, 3]])

# Calcular autovalores y autovectores
autovalores, autovectores = np.linalg.eig(M)
print("Autovalores:", autovalores)
print("Autovectores:\n", autovectores)

# Descomposición en valores singulares
U, S, VT = np.linalg.svd(M)
print("Matriz U:\n", U)
print("Valores Singulares (S):", S)
print("Matriz VT:\n", VT)


Solución del sistema de ecuaciones (valores de x y y): [2.2 1.2]
Autovalores: [5. 2.]
Autovectores:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
Matriz U:
 [[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]
Valores Singulares (S): [5.11667274 1.95439508]
Matriz VT:
 [[-0.76775173 -0.64074744]
 [-0.64074744  0.76775173]]


La función `random.rand` en Python es una forma de crear números al azar, como si fuera un "dado digital" que genera números entre 0 y 1. Es como tener una caja mágica que, cada vez que la usas, te da un número diferente.

Aquí te explico cómo se usa y algunos ejemplos para entenderla mejor:

### Paso 1: Importar la Biblioteca
Primero, necesitamos importar la biblioteca **NumPy** para usar `random.rand`:
```python
import numpy as np
```

### Ejemplo 1: Generar un Número al Azar
Si queremos que la caja mágica nos dé un solo número entre 0 y 1, hacemos esto:
```python
# Crear un número al azar entre 0 y 1
numero = np.random.rand()
print("Número al azar:", numero)
```
Cada vez que ejecutas este código, te dará un número distinto, por ejemplo: 0.523 o 0.879.

### Ejemplo 2: Generar una Lista de Números al Azar
Podemos pedirle a `random.rand` que nos dé varios números a la vez. Si queremos 5 números, por ejemplo:
```python
# Crear 5 números al azar entre 0 y 1
numeros = np.random.rand(5)
print("Lista de números al azar:", numeros)
```
Te dará algo como `[0.4, 0.7, 0.2, 0.8, 0.5]`. Cada número será distinto cada vez que corras el código.

### Ejemplo 3: Crear una "Tabla" o Matriz de Números al Azar
También podemos usar `random.rand` para crear una tabla (o matriz) de números. Imagina una tabla de multiplicar, pero con números al azar en lugar de multiplicaciones.

Si queremos una tabla de 3 filas y 2 columnas:
```python
# Crear una matriz de 3 filas y 2 columnas con números al azar
matriz = np.random.rand(3, 2)
print("Matriz de números al azar:\n", matriz)
```

Cada vez que corras el código, obtendrás una matriz distinta, como:
```
[[0.6 0.2]
 [0.1 0.8]
 [0.9 0.4]]
```

### ¿Para Qué Sirve `random.rand`?

- **Simulaciones**: Se usa en simulaciones, como si quieres simular el lanzamiento de dados o cualquier evento al azar.
- **Juegos**: Para crear eventos inesperados en videojuegos, como aparecer un objeto en un lugar aleatorio.
- **Ciencia de Datos y Estadística**: Los científicos y programadores lo usan para crear datos de prueba o para hacer cálculos donde los números aleatorios son útiles.

Es como tener un "dado digital" que puedes configurar de muchas maneras para crear números al azar, ¡una herramienta divertida y poderosa en Python!